title: Digital Agathemerus
description: A repository for a digital edition of Agathemerus' "Sketch of Geography"
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
